### ISSUE TITLE
Introduction: Github 

### ISSUE THREAD

**Issue by rivera-lanasm** [Students-Using-Data-for-Social-Good/dhs_provider990#1]
A brief tutorial to Git: https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

**Steps:**
- install git on local machine
    - for windows: https://git-scm.com/download/win
    - for mac: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
- create github account and share with me
- accept invitation to join organization
- navigate to code repository: https://github.com/Students-Using-Data-for-Social-Good/dhs_provider990/
- git clone repository
    - command: `git clone  https://github.com/Students-Using-Data-for-Social-Good/dhs_provider990.git`
    - this will copy 1) the contents of the up to date code wherever you run the command and 2) initialize git tracking on your local machine 
- create file under /introductions/<name>.txt with a short sentence about the topics you'd like to learn about during this project
- use `git status` to verify changes to the code have been made 
    - you should see a reference to the file you just created
- git staging: git "add" the file you created
    - `git add dhs_provider990/introductions/miguel.txt` 
- use `git status` to verify that changes have been "staged"
- git commit: create a commit with `git commit -m "useful message"`
- push changes to remote repo: `git push origin main`

**Comment by goelaine** [comment]
i'm having trouble on the last step -- with pushing my changes. it's giving me this error:
fatal: unable to access 'https://github.com/Students-Using-Data-for-Social-Good/dhs_provider990.git/': The requested URL returned error: 403
I did skip over the accept invitation to join organization for now -- is that why this is happening?
